// tokensDefs.h
// ~~~~~~~~~~
/* This defines the token registry. The structure is similar to that of Clang's
 * token registry */

#ifndef TOKEN
#define TOKEN(X)
#endif
#ifndef TOKEN_PUNCTUATOR
#define TOKEN_PUNCTUATOR(NAME, SEQ) TOKEN(NAME)
#endif

// General Tokens
TOKEN(UNKNOWN)
TOKEN(EOF)
TOKEN(NUM)
TOKEN(ID)
TOKEN(STR_LITERAL)

// Punctuators
TOKEN_PUNCTUATOR(ASSIGN, "=")
TOKEN_PUNCTUATOR(EQUAL, "==")
TOKEN_PUNCTUATOR(NOTEQUAL, "!=")
TOKEN_PUNCTUATOR(LESSTHAN, "<")
TOKEN_PUNCTUATOR(LESSEQUALTHAN, "<=")
TOKEN_PUNCTUATOR(GREATERTHAN, ">")
TOKEN_PUNCTUATOR(GREATEREQUALTHAN, ">=")
TOKEN_PUNCTUATOR(LPAREN, "(")
TOKEN_PUNCTUATOR(RPAREN, ")")
TOKEN_PUNCTUATOR(LBRACE, "{")
TOKEN_PUNCTUATOR(RBRACE, "}")
TOKEN_PUNCTUATOR(DOT, ".")
TOKEN_PUNCTUATOR(COMMA, ",")
TOKEN_PUNCTUATOR(PLUS, "+")
TOKEN_PUNCTUATOR(MINUS, "-")
TOKEN_PUNCTUATOR(MULT, "*")
TOKEN_PUNCTUATOR(DIV, "/")
